version: '3'

services:
  db:
    container_name: postgresdb_homeInventory
    image: postgres:latest
    restart: always
    env_file:
      - project.env
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  webhi:
    container_name: django_homeInventory
    build: app/
    command: >
      bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py collectstatic --no-input && gunicorn home.wsgi:application --bind 0.0.0.0:8000 --workers=4"
    env_file:
      - project.env
    expose:
      - 8000
    depends_on:
      - db
    volumes:
      - staticfiles:/home/app/web/staticfiles
      - mediafiles:/home/app/web/mediafiles
  nginx:
    container_name: nginx_homeInventory
    build: ./nginx
    restart: always
    ports:
      - 8000:80

    volumes:
      - ./nginx:/etc/nginx/conf.d
      - staticfiles:/home/app/web/staticfiles/
      - mediafiles:/home/app/web/mediafiles/
    depends_on:
      - webhi
volumes:
  postgres-data:
  staticfiles:
  mediafiles:
