version: '3.3'

services:
  webhisq:
    container_name: django_homeInventorysq
    build: homeInventoryManager/
    command: >
      bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py collectstatic --no-input && gunicorn home.wsgi:application --bind 0.0.0.0:8000 --workers=4"
    env_file:
      - ./project.env
    expose:
      - 8000
    volumes:
      - staticfiles:/home/app/web/staticfiles
      - mediafiles:/home/app/web/mediafiles
      - sqlitedb:/home/app/web/home/db/
  nginxsq:
    container_name: nginx_homeInventorysq
    build: ./nginx
    restart: always
    expose:
      - 80

    volumes:
      - ./nginx:/etc/nginx/conf.d
      - staticfiles:/home/app/web/staticfiles/
      - mediafiles:/home/app/web/mediafiles/
    depends_on:
      - webhisq
volumes:
  staticfiles:
  mediafiles:
  sqlitedb:
networks:
  default:
    external:
      name: nginxproxymanager_default
