# Generated by Django 3.2.4 on 2021-07-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='description',
            field=models.CharField(blank=True, help_text='Short description of the location. Ex: "office supplies", "model trains", "small electronic parts"', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='type',
            field=models.CharField(blank=True, choices=[('Shelf', 'Shelf'), ('Drawer', 'Drawer'), ('Cabinet', 'Cabinet'), ('Box', 'Box')], default='----', max_length=30, null=True),
        ),
    ]
